import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { FromBTCLNSwap, FromBTCSwap, IToBTCSwap } from "sollightning-sdk";
import { getCurrencySpec, getNativeCurrency, toHumanReadableString } from "../utils/Currencies";
export function FeeSummaryScreen(props) {
    let className = props.className;
    if (props.swap instanceof IToBTCSwap) {
        const currency = getCurrencySpec(props.swap.getToken());
        return (_jsxs("div", { className: className, children: [_jsxs("div", { className: "d-flex my-2", children: [_jsx("span", { children: "Amount:" }), _jsxs("span", { className: "ms-auto", children: [toHumanReadableString(props.swap.getInAmountWithoutFee(), currency), " ", currency.ticker] })] }), _jsxs("div", { className: "d-flex my-2", children: [_jsx("span", { children: "Swap fee:" }), _jsxs("span", { className: "ms-auto", children: [toHumanReadableString(props.swap.getSwapFee(), currency), " ", currency.ticker] })] }), _jsxs("div", { className: "d-flex my-2", children: [_jsx("span", { children: "Network fee:" }), _jsxs("span", { className: "ms-auto", children: [toHumanReadableString(props.swap.getNetworkFee(), currency), " ", currency.ticker] })] }), _jsxs("div", { className: "d-flex fw-bold border-top border-light font-bigger", children: [_jsx("span", { children: "Total:" }), _jsxs("span", { className: "ms-auto d-flex align-items-center", children: [_jsx("img", { src: currency.icon, className: "currency-icon-small" }), toHumanReadableString(props.swap.getInAmount(), currency), " ", currency.ticker] })] })] }));
    }
    if (props.swap instanceof FromBTCSwap) {
        const currency = getCurrencySpec(props.swap.getToken());
        return (_jsxs("div", { className: className, children: [_jsxs("div", { className: "d-flex my-2", children: [_jsx("span", { children: "Amount:" }), _jsxs("span", { className: "ms-auto", children: [toHumanReadableString(props.swap.getOutAmountWithoutFee(), currency), " ", currency.ticker] })] }), _jsxs("div", { className: "d-flex my-2", children: [_jsx("span", { children: "Swap fee:" }), _jsxs("span", { className: "ms-auto", children: [toHumanReadableString(props.swap.getFee(), currency), " ", currency.ticker] })] }), _jsxs("div", { className: "d-flex my-2", children: [_jsx("span", { children: "Watchtower fee:" }), _jsxs("span", { className: "ms-auto", children: [toHumanReadableString(props.swap.getClaimerBounty(), getNativeCurrency()), " ", getNativeCurrency().ticker] })] }), _jsxs("div", { className: "d-flex fw-bold border-top border-light font-bigger", children: [_jsx("span", { children: "Total:" }), _jsxs("span", { className: "ms-auto d-flex align-items-center", children: [_jsx("img", { src: currency.icon, className: "currency-icon-small" }), toHumanReadableString(props.swap.getOutAmount(), currency), " ", currency.ticker] })] })] }));
    }
    if (props.swap instanceof FromBTCLNSwap) {
        const currency = getCurrencySpec(props.swap.getToken());
        const isApproximate = props.swap.data.getAmount() == null;
        return (_jsxs("div", { className: className, children: [_jsxs("div", { className: "d-flex my-2", children: [_jsx("span", { children: "Amount:" }), _jsxs("span", { className: "ms-auto", children: [isApproximate ? "~" : "", toHumanReadableString(props.swap.getOutAmountWithoutFee(), currency), " ", currency.ticker] })] }), _jsxs("div", { className: "d-flex my-2", children: [_jsx("span", { children: "Swap fee:" }), _jsxs("span", { className: "ms-auto", children: [toHumanReadableString(props.swap.getFee(), currency), " ", currency.ticker] })] }), _jsxs("div", { className: "d-flex fw-bold border-top border-light font-bigger", children: [_jsx("span", { children: "Total:" }), _jsxs("span", { className: "ms-auto d-flex align-items-center", children: [_jsx("img", { src: currency.icon, className: "currency-icon-small" }), isApproximate ? "~" : "", toHumanReadableString(props.swap.getOutAmount(), currency), " ", currency.ticker] })] })] }));
    }
    return null;
}
